name: cognition
channels: 
  - anaconda
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - einops
  - jupyter
  - python=3.9
  - pytorch
  - pytest
  - pandas
  - scikit-learn
  - scikit-survival
  - seaborn
  - torchvision
  - tqdm
  - python-box
  - pip
  - pip:
      - h5py
      - invoke
      - lifelines
      - torchsummary
      - torch_optimizer
      - wandb
      - openslide-python
      - opencv-python