name: cognition
channels: 
  - anaconda
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - einops==0.6.0
  - jupyter==1.0.0
  - python=3.9
  - pytorch==1.13.1
  - pandas==1.5.3
  - scikit-learn==1.0.2
  - seaborn==0.11.2
  - torchvision==0.14.1
  - tqdm==4.64.1
  - pip==23.0
  - pip:
      - torchsummary==1.5.1
      - wandb==0.13.11
      - openslide-python==1.2.0