name: cognition
channels: 
  - anaconda
  - conda-forge
  - defaults
  - pytorch
dependencies:
#  - cudatoolkit==11.8.0
  - einops==0.6.0
  - jupyter==1.0.0
  - python=3.9
  - pytorch==1.13.1
  - pytorch-cude==11.8.0
  - pandas==1.5.3
  - scikit-learn==1.0.2
  - scikit-survival==0.20.0
  - seaborn==0.11.2
  - torchvision==0.14.1
  - tqdm==4.64.1
  - python-box==7.0.0
  - pip==23.0
  - pip:
      - h5py==3.8.0
      - invoke==2.0.0
      - lifelines==0.27.7
      - torchsummary==1.5.1
      - torch_optimizer==0.3.0
      - wandb==0.15.8
      - openslide-python==1.2.0
      - opencv-python==4.7.*