data_path: /net/archive/export/tcga
tcga_path: /net/archive/export/tcga/tcga
gdc_client: /home/kh701/gdc-client
log_path: /home/kh701/pycharm/x-perceiver/logs
seed: 42

wandb: True

data:
  level: 3

task: classification # [survival, classification]
sources:
  - omic
#  - slides

survival: # all parameters related to survival task
  loss: nll # valid: nll, ce_survival, cox

clf:
  n_classes: 4


train_loop:
  checkpoint_interval: 1
  eval_interval: 10
  batch_size: 1
  epochs: 30

optimizer:
  max_lr: 0.005
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.001 # or None


model_params:
  output_dims: 4
  weight_decay: True
  class_weights: True # weight classes by inverse frequency

