data_path: /net/archive/export/tcga
tcga_path: /net/archive/export/tcga/tcga
gdc_client: /home/kh701/pycharm/x-perceiver/gdc-client
log_path: /home/kh701/pycharm/x-perceiver/logs
seed: 1
hyperparams: config/best_hyperparams.yml

dataset: blca #  [blca, brca, ucec, kirp]
model: healnet # [fcnn, healnet, healnet_early, mcat]

n_folds: 5

wandb: True

data:
  # image preprocessing
  resize: True # ONLY use for debugging - manually resize images
  resize_height: 1024 # if resize is True
  resize_width: 1024 # if resize is True
  patch_size: 256 # don't changed if used for pre-processing
#  wsi_level: 2 # WSI resolution level (if available)
  prefetch: False


task: survival # [survival, classification]
sources:
#  - omic
  - slides


survival: # all parameters related to survival task
  loss: nll # valid: nll, ce_survival, cox
  subset: uncensored # subset used to calculate survival bin cutoffs, valid: all, censored, uncensored

train_loop:
  checkpoint_interval: 5
  eval_interval: 1
  batch_size: 4
  epochs: 100
  # early stopping
  patience: 7

optimizer:
  max_lr: 0.005
  lr: 0.002
  momentum: 0.92
  weight_decay: 0.00026 # or None


# model_params are specified in config/best_hyperparams.yml