data_path: /net/archive/export/tcga
tcga_path: /net/archive/export/tcga/tcga
gdc_client: /home/kh701/gdc-client
log_path: /home/kh701/pycharm/x-perceiver/logs

data:
  level: 3

model:
  checkpoint_interval: 1
  batch_size: 1
  epochs: 10
  max_lr: 0.005
  lr: 0.001
  momentum: 0.9


