data_path: /net/archive/export/tcga
tcga_path: /net/archive/export/tcga/tcga
gdc_client: healnet/gdc-client
log_path: healnet/logs
seed: 1
hyperparams: config/best_hyperparams.yml

dataset: kirp #  [blca, brca, ucec, kirp]
model: healnet # [fcnn, healnet, healnet_early, mcat]

explainer: False
missing_ablation: False
omic_attention: False # switch off omic attention (debug mode)

n_folds: 5

wandb: True # log to weights and biases (login required)


data:
  # Parameters for running on raw WSIs
  resize: True #
  resize_height: 1024 # if resize is True
  resize_width: 1024 # if resize is True
  wsi_level: 2 # WSI resolution level (if available)
  # Parameters for patch pre-processing
  patch_size: 256 # don't change if used for pre-processing

sources: # select which data sources to use, list of string, valid values: omic, slides
  - omic
  - slides

survival: # all parameters related to survival task
  loss: nll # valid: nll, ce_survival, cox
  subset: uncensored # subset used to calculate survival bin cutoffs, valid: all, censored, uncensored

train_loop:
  eval_interval: 1 # evaluate on validation set every n epochs
  batch_size: 4
  epochs: 50 # max training epochs
  early_stopping: True # stop training if validation loss doesn't improve for `patience` epochs
  patience: 5 # number of epochs to wait for improvement before stopping training

optimizer:
  max_lr: 0.008 # maximum learning rate for OneCycleLR scheduler
  lr: 0.007765016508403882 # used for all
  momentum: 0.92 # momentum
  weight_decay: None # L2 regularisation


# other `model_params` are specified in config/best_hyperparams.yml