data_path: /net/archive/export/tcga
tcga_path: /net/archive/export/tcga/tcga
gdc_client: /home/kh701/gdc-client
log_path: /home/kh701/pycharm/x-perceiver/logs
seed: 42

wandb: True

data:
  level: 3

task: classification # [survival, classification]
sources:
  - omic
#  - slides

model: perceiver

survival: # all parameters related to survival task
  loss: nll # valid: nll, ce_survival, cox

clf:
  n_classes: 4


train_loop:
  checkpoint_interval: 10
  eval_interval: 10
  batch_size: 8
  epochs: 10

optimizer:
  max_lr: 0.005
  lr: 0.001
  momentum: 0.9
  weight_decay: 0.0001 # or None


model_params:
  output_dims: 4
  weight_decay: True
  class_weights: True # weight classes by inverse frequency
  num_freq_bands: 6
  depth: 6
  max_freq: 2.
  num_latents: 32
  latent_dim: 32
  cross_dim_head: 16
  latent_dim_head: 16
  cross_heads: 1
  latent_heads: 8
  attn_dropout: 0.5
  ff_dropout: 0.5
  fourier_encode_data: True
  self_per_cross_attn: 1


