method: grid
metric:
  goal: maximize
  name: val_f1
parameters:
  model_params.weight_decay:
    values:
      - 0
      - 0.0001
      - 0.0005
  model_params.num_freq_bands:
    values:
      - 2
      - 8
  model_params.depth:
    values:
      - 1
      - 3
      - 5
  model_params.max_freq:
    values:
      - 2.
      - 8.
  model_params.num_latents:
    values:
      - 4
      - 16
      - 32
      - 64
  model_params.latent_dim:
    values:
      - 4
      - 16
      - 32
      - 64
  model_params.attn_dropout:
    values:
      - 0
      - 0.5
      - 0.25
  model_params.ff_dropout:
    values:
      - 0
      - 0.5
      - 0.25
  optimizer.lr:
    values:
      - 0.002
      - 0.001
      - 0.0005
  optimizer.momentum:
    values:
      - 0.9
      - 0.95
      - 0.8
program: x_perceiver/main.py