method: bayes
metric:
  goal: maximize
  name: mean_test_c_index
parameters:
  sources:
    values:
      - omic
      - slides
  n_folds:
    value: 5
  train_loop.epochs:
      value: 50
  train_loop.patience:
      value: 5
  train_loop.batch_size:
      value: 8
  model_params.l1:
    distribution: uniform
    min: 0.0
    max: 0.0005
  model_params.depth:
    distribution: int_uniform
    min: 2
    max: 5
  model_params.num_latents:
    distribution: int_uniform
    min: 8
    max: 32
  model_params.latent_dim:
    distribution: int_uniform
    min: 16
    max: 128
  model_params.cross_dim_head:
    distribution: int_uniform
    min: 16
    max: 128
  model_params.latent_dim_head:
    distribution: int_uniform
    min: 16
    max: 128
  model_params.attn_dropout:
    distribution: uniform
    min: 0.0
    max: 0.5
  model_params.ff_dropout:
    min: 0.0
    max: 0.5
  optimizer.lr:
    distribution: uniform
    min: 0.0001
    max: 0.01
program: x_perceiver/main.py