method: bayes
metric:
  goal: maximize
  name: mean_val_c_index
parameters:
  model_params.l1:
    distribution: uniform
    min: 0.0
    max: 0.0005
  model_params.depth:
    distribution: int_uniform
    min: 2
    max: 4
  model_params.num_latents:
    distribution: int_uniform
    min: 4
    max: 16
  model_params.latent_dim:
    distribution: int_uniform
    min: 4
    max: 128
  model_params.cross_dim_head:
    distribution: int_uniform
    min: 16
    max: 128
  model_params.latent_dim_head:
    distribution: int_uniform
    min: 16
    max: 128
program: x_perceiver/main.py