method: bayes
metric:
  goal: maximize
  name: mean_test_c_index
sources:
  value:
    - slides
n_folds:
  value: 3
parameters:
  model_params.l1:
    distribution: uniform
    min: 0.0
    max: 0.0005
  model_params.depth:
    distribution: int_uniform
    min: 2
    max: 5
  model_params.num_latents:
    distribution: int_uniform
    min: 8
    max: 32
  model_params.latent_dim:
    distribution: int_uniform
    min: 16
    max: 128
  model_params.cross_dim_head:
    distribution: int_uniform
    min: 16
    max: 128
  model_params.latent_dim_head:
    distribution: int_uniform
    min: 16
    max: 128
  model_params.attn_dropout:
    distribution: uniform
    min: 0.0
    max: 0.5
  model_params.ff_drouput:
    min: 0.0
    max: 0.5
program: x_perceiver/main.py